name: colors
description: Flutter Color Generation.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  app_settings: ^4.2.0
  cupertino_icons: ^1.0.5
  easy_localization: ^3.0.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_easyloading: ^3.0.5
  flutter_native_splash: ^2.2.17
  flutter_secure_storage: ^7.0.1
  hive_flutter: ^1.1.0
  image_picker: ^0.8.6+1
  permission_handler: ^10.2.0
  shared_preferences: ^2.0.17

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0
  solid_lints: ^0.0.13

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/fonts/
    - assets/translations/
  fonts:
    - family: Courgette
      fonts:
        - asset: assets/fonts/Courgette/Courgette-Regular.ttf

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: assets/images/logo.png
  background_color: "#246EE9"
  min_sdk_android: 21
  web:
    generate: true
    image_path: assets/images/logo.png
    background_color: "#246EE9"
    theme_color: "#ffffff"
  windows:
    generate: true
    image_path: assets/images/logo.png
    icon_size: 48
  macos:
    generate: true
    image_path: assets/images/logo.png

flutter_native_splash:
  color: "#246EE9"
  fullscreen: true
  image: assets/images/logo.png
